version: '3'
services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5433:5432' # Cambia el puerto externo para evitar conflictos con "teslo2.0"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_NAME}_db
    volumes:
      - ./users_data:/var/lib/postgresql/data
